### ISSUE TITLE
ec2 instance fails to signal completion

### ISSUE THREAD

**Issue by jyjohnson** [aws-samples/amazon-chime-pstn-audio-with-amazon-lex-ivr#172]
### Describe the issue

The Asterisk instance fails to signal cfn completion... that causes the stack to fail and then delete. What should we look? 

Also, there are hard-coded IPs in asterisk.ts - should those be dynamic? 

### Steps to Reproduce

run the cdk and wait until it fails

### Current behavior

ec2 instance comes online but does not signal completion

### AWS SDK version used

3.325+

### Operating System and version

cloud9

**Comment by schuettc** [comment]
Updated Asterisk to use Ubuntu and more quickly build.  cfn-signal is used to return results to Cloudformation.  

Hard coded IPs in `asterisk.ts` are the IPs for Amazon Chime SDK Voice Connector defined here and required: https://docs.aws.amazon.com/chime-sdk/latest/ag/network-config.html#cvc
